-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyYLlZjCmUriJ6d4w
xg2zRSde2pNrx1GQ4Qy0c+iw5AKgCgYIKoZIzj0DAQehRANCAARGED+7uo0YsYJp
KDcRJXkeNv8UqQF6hl6TB7ftyfAbKc7jmpcTI7Q2VXxaWlEwa/DSQAnZYhwqKmqt
JE/bLoKV
-----END PRIVATE KEY-----